# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Reactive form' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveCocoa'
  pod 'lottie-ios'
  # Pods for Reactive form

  target 'Reactive formTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Reactive formUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
